// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAosHN80Nwey2CVDbkgMyhq8yWus7b_2T0',
    appId: '1:153023806025:web:9179ec2f0c496ad2be5d98',
    messagingSenderId: '153023806025',
    projectId: 'flutter-chat-app-bf817',
    authDomain: 'flutter-chat-app-bf817.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bf817.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnzFvkPuRRI_iiWGZaZp_K4fMB01ed0aY',
    appId: '1:153023806025:android:fba24fadfb1eb0d5be5d98',
    messagingSenderId: '153023806025',
    projectId: 'flutter-chat-app-bf817',
    storageBucket: 'flutter-chat-app-bf817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3cL7OO6szdW3RguLB3f4UI64k_9cVnhE',
    appId: '1:153023806025:ios:cbf8a7ca88dee08bbe5d98',
    messagingSenderId: '153023806025',
    projectId: 'flutter-chat-app-bf817',
    storageBucket: 'flutter-chat-app-bf817.appspot.com',
    iosBundleId: 'com.example.flutterChatApp1212',
  );

}